### ISSUE TITLE
Tabs not working with newest Gutenberg Version 8.6.0

### ISSUE THREAD

**Issue by nikwins** [nk-o/ghostkit#102]
With the newest versions of Gutenberg (8.6.0) the ghostkit tabs block isn't working properly anymore. If you set a tabs block in the backend, the button to add content to the tabs isn't showing anymore.
![image](https://user-images.githubusercontent.com/13330242/88677228-50d22f80-d0ed-11ea-9ef9-616f6bc09186.png)

Adding/deleting tabs still works, but you can't add content to the tabs.
I think the problem is, that the `.is-selected` class doesn't get set anymore. 
![image](https://user-images.githubusercontent.com/13330242/88677758-f7b6cb80-d0ed-11ea-8dd9-5e9537a0f8f8.png)

Here is the console error that occurs when adding a tabs block:
```
Warning: React does not recognize the `%s` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `%s` instead. If you accidentally passed it from a parent component, remove it from the DOM element.%s
```

**Comment by nikwins** [comment]
Update:
Since the WordPress 5.5 Update that also included a newer version of Gutenberg, the ghostkit tabs aren't working anymore.

**Comment by stefanfisk** [comment]
I am encountering this issue in v2.14.0. From what I can tell the issue is that `removeBlock()` is a NOOP because `InnerBlocks` of `blocks/tabs` is locked: https://github.com/WordPress/gutenberg/blob/ffa22b8bace0b65d412d205cfd89b1b5d85834eb/packages/block-editor/src/store/actions.js#L617.

When removing a tab, it is only removed from `tabsData`, but the inner block remains. 

And since the inner block remains new blocks are not created until the old tab count is exceeded, and then only after updating and reloading the page.

I was looking at your code because I wanted to implement a similar block, and sadly I have no idea on how to fix the issue except for unlocking the template.
