### ISSUE TITLE
Countdown Unit Labels not translateable

### ISSUE THREAD

**Issue by silvanarnet** [nk-o/ghostkit#116]
I have tried it with WMPL and Logo Translate but it didn't work.

**Comment by nk-o** [comment]
Hey.  
  
I don't think it is something, that should be translated using WPML. This is more like Loco Translate work. But since it does not support Gutenberg blocks translation, you can only translate strings manually. Read here a small example of how to make translations - https://github.com/nk-o/ghostkit/blob/master/src/languages/readme.md
