### ISSUE TITLE
Saving columns image background as editor Bug

### ISSUE THREAD

**Issue by spencer-j** [nk-o/ghostkit#58]
Hello ghostkit team.

the background color of a ghostkit col is not saved if im logged in with editor capabilities. As Admin it works as expected.
thanks spencer

**Comment by nk-o** [comment]
Hi.

I can't repeat it with the latest Gutenberg plugin. Column backgrounds just work:

![image](https://user-images.githubusercontent.com/14810891/60269161-99218b80-98f6-11e9-8c5a-cda24a7aca45.png)

![image](https://user-images.githubusercontent.com/14810891/60269219-b2c2d300-98f6-11e9-8777-ec46a2ce0c63.png)

**Comment by nk-o** [comment]
Aha, I see the problem with Image background loading.

**Comment by spencer-j** [comment]
Hello nk-o,
is there a chance that you fix this bug soon, otherwise at the moment, its not so usefull in production sites.
Thanks spencer

**Comment by nk-o** [comment]
Will be fixed, but this is not so easy. I have tested and seen, that WordPress removed some <img> tag attributes if the user has no permissions.

The only solution for now - is to change saved attributes to a single ID and Url of the selected image.

But since we use the plugin on production, we may break some user's sites. So, we need a fallback and a solution, that will avoid future bugs.

I will work on it this week.

**Comment by spencer-j** [comment]
This are cool news, thank you.
ghostkit is top
